services:
  webserver:
    container_name: belvedereapp-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: thebelvedereglacier-webserver-dev:latest
    volumes:
      - ./app:/var/www/html # Mount the local directory to /var/www/html in the container
    environment:
      - DBHOST=${DBHOST}
      - DBNAME=${DBNAME}
      - DBUSERNAME=${DBUSERNAME}
      - DBPORT=${DBPORT}
      - DBSSLMODE=${DBSSLMODE}
      - DBPASSWORD=${DBPASSWORD}
    networks:
      - public-net
      - infra-net

networks:
  public-net:
    external: true
  infra-net:
    external: true
